config/routes.rb
Rails.application.routes.draw do
  # 顧客側deviseのルーティング
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用deviseのルーティング
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 顧客側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get 'about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/check' => 'customers#check'
    patch 'customers/withdrawl' => 'customers#withdrawl', as: 'withdrawal'
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    resources :orders, only: [:new, :index, :show, :create]
    post 'orders/check' => 'orders#check'
  end

  # 管理者側のルーティング設定
  namespace :admin do
    get 'homes/top'
    resources :items, only: [:new, :index, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :order_items
  has_many :cart_items, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :price, numericality: true
  validates :image, presence: true

  # 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end

  def get_image(width, height)
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container mt-3">
  <h3 class="mb-5">商品編集</h3>

  <% if @item.errors.any? %>
    <%= @item.errors.count %>件のエラーが発生しました
    <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with model: @item, url: "/admin/items/#{@item.id}" do |f| %>
  <div class="row form-group">
    <label class="col-lg-2">商品画像</label>
    <%= f.file_field :image, accept: "image/*" %>
  </div>

  <div class="row form-group">
    <label class="col-lg-2">商品名</label>
    <%= f.text_field :name, class:"form-control col-lg-5" %>
  </div>

  <div class="row form-group">
    <label class="col-lg-2">商品説明</label>
    <%= f.text_area :introduction, class:"form-control col-lg-5" %>
  </div>

  <div class="row form-group">
    <label class="col-lg-2">税抜価格</label>
    <%= f.text_field :price, class:"form-control col-lg-3" %>円
  </div>

    <%= f.submit '変更を保存', class:"btn btn-success mt-4" %>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container mt-3">
  <div class="row">
    <h3 class="col">商品一覧</h3>

    <h4><%= link_to "＋", new_admin_item_path, class:"text-right btn btn-outline-secondary" %></h4>
  </div>
  <br>

  <table class="table">
  <thead>
    <tr class="table-secondary">
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜き価格</th>
    </tr>
  </thead>
  <% @items.each do |item| %>
  <tbody>
    <tr>
      <td><%= item.id %></td>
      <td><%= link_to item.name, admin_item_path(item.id), class:"border-bottom text-secondary" %></td>
      <td><%= item.price.to_s(:delimited) %></td>
    </tr>
  </tbody>
  <% end %>
</div>

app/views/admin/items/new.html.erb
<div class="container mt-3">
  <h3 class="mb-5">商品新規登録</h3>

  <% if @item.errors.any? %>
    <%= @item.errors.count %>件のエラーが発生しました
    <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with model: @item, url: '/admin/items' do |f| %>
    <div class="row form-group">
      <label class="col-lg-2">商品画像</label>
      <%= f.file_field :image, accept: "image/*" %>
    </div>

    <div class="row form-group">
      <label class="col-lg-2">商品名</label>
      <%= f.text_field :name, class:"form-control col-lg-5" %>
    </div>

    <div class="row form-group">
      <label class="col-lg-2">商品説明</label>
      <%= f.text_area :introduction, class:"form-control col-lg-5" %>
    </div>

    <div class="row form-group">
      <label class="col-lg-2">税抜価格</label>
      <%= f.text_field :price, class:"form-control col-lg-3" %>円
    </div>

    <%= f.submit '新規登録', class:"btn btn-success mt-4" %>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container mt-3">
  <h3 class="mb-4">商品詳細</h3>

  <div class="row">
    <div class="col-lg-4 mt-2">
      <%= image_tag @item.get_image(300,300) %>
    </div>

    <div class="col-lg-8 mt-2">
      <div class="row mt-4">
        <h6 class="col-lg-3">商品名</h6>
        <h5 class="col-lg"><%= @item.name %></h5>
      </div>

      <div class="row mt-2">
        <h6 class="col-lg-3">商品説明</h6>
        <h5 class="col-lg"><%= @item.introduction %></h5>
      </div>

      <div class="row mt-2">
        <h6 class="col-lg-3">税抜価格<br>(税込価格)</h6>
        <h5 class="col-lg"><%= @item.price.to_s(:delimited) %>(<%= @item.with_tax_price.to_s(:delimited) %>)円</h5>
      </div>
    </div>
  </div>
  <%= link_to "編集する", edit_admin_item_path(@item.id), class:"btn btn-success mt-4" %>
</div>