config/routes.rb
Rails.application.routes.draw do
  # 顧客側deviseのルーティング
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用deviseのルーティング
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 顧客側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get 'about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/check' => 'customers#check'
    patch 'customers/withdrawl' => 'customers#withdrawl', as: 'withdrawal'
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    resources :orders, only: [:new, :index, :show, :create]
    post 'orders/check' => 'orders#check'
  end

  # 管理者側のルーティング設定
  namespace :admin do
    get 'homes/top'
    resources :items, only: [:new, :index, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, presence: true

  def customer_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end
  end

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    else
      render "admin/customers/edit"
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container  mt-3">
  <h3 class="mb-4"><%= @customer.last_name %><%= @customer.first_name %>の会員情報編集</h3>

  <% if @customer.errors.any? %>
    <%= @customer.errors.count %>件のエラーが発生しました
    <ul>
    <% @customer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>


  <%= form_with model: @customer, url: "/admin/customers/#{@customer.id}" do |f| %>
  <form>
    <div class="row">
      <div class="col-lg-2">
        <label>会員ID</label>
      </div>
      <div class="col-lg-3">
        <%= @customer.id %>
      </div>
    </div>
    <br>
    <div class="form-group row">
      <div class="col-lg-2">
        <label>氏名</label>
      </div>
      <div class="col-lg-3">
        <%= f.text_field :last_name, class:"form-control" %>
      </div>
      <div class="col-lg-3">
        <%= f.text_field :first_name, class:"form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-lg-2">
        <label>フリガナ</label>
      </div>
      <div class="col-lg-3">
        <%= f.text_field :last_name_kana, class:"form-control" %>
      </div>
      <div class="col-lg-3">
        <%= f.text_field :first_name_kana, class:"form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-lg-2">
        <label>郵便番号</label>
      </div>
      <div class="col-lg-3">
        <%= f.text_field :postal_code, class:"form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-lg-2">
        <label>住所</label>
      </div>
      <div class="col-lg-8">
        <%= f.text_field :address, class:"form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-lg-2">
        <label>電話番号</label>
      </div>
      <div class="col-lg-3">
        <%= f.text_field :telephone_number, class:"form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-lg-2">
        <label>メールアドレス</label>
      </div>
      <div class="col-lg-3">
        <%= f.text_field :email, class:"form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-lg-2">
        <label>会員ステータス</label>
      </div>
      <div class="form-check form-check-inline">
        <%= f.radio_button :is_deleted, :false, class:"form-check-input" %>
        <label class="form-check-label" for="inlineRadio1">有効</label>
      </div>
      <div class="form-check form-check-inline">
        <%= f.radio_button :is_deleted, :true, class:"form-check-input" %>
        <label class="form-check-label" for="inlineRadio2">退会</label>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-2"></div>
      <%= f.submit '変更を保存', class:"btn btn-block btn-success col-2" %>
      <div class="col-lg-8"></div>
    </div>
  </form>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container mt-3">
  <h3 class="col">会員一覧</h3>

  <table class="table">
    <thead>
      <tr class="table-secondary">
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>

    <% @customers.each do |customer| %>
    <tbody>
      <tr>
        <th scope="row"><%= customer.id %></th>
        <td>
        <%= link_to admin_customer_path(customer.id), class:"border-bottom text-secondary" do %>
          <%= customer.last_name %><%= customer.first_name %>
        <% end %>
        </td>
        <td><%= customer.email %></td>
        <td><%= customer.customer_status %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

app/views/admin/customers/show.html.erb
<div class="container mt-3">

  <h3 class="mb-4"><%= @customer.last_name %><%= @customer.first_name %>の会員詳細</h3>

  <div class="row">
    <div class="col-lg-2">
      <p>会員ID</p>
      <p>氏名</p>
      <p>フリガナ</p>
      <p>郵便番号</p>
      <p>住所</p>
      <p>電話番号</p>
      <p>メールアドレス</p>
      <p>会員ステータス</p>
    </div>

    <div class="col-lg">
      <p><%= @customer.id %></p>
      <p><%= @customer.last_name %><%= @customer.first_name %></p>
      <p><%= @customer.last_name_kana %><%= @customer.first_name_kana %></p>
      <p><%= @customer.postal_code %></p>
      <p><%= @customer.address %></p>
      <p><%= @customer.telephone_number %></p>
      <p><%= @customer.email %></p>
      <p><%= @customer.customer_status %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-2">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-success mt-3" %>
    </div>
    <%= link_to "注文履歴一覧を見る", admin_order_path(@customer.id), class:"btn btn-primary mt-3" %>
  </div>
</div>